# Generated by Django 6.0.5 on 2026-05-30 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_usuario_responsavel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
